# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_ml_config.ui'
#
# Created: Fri Jan 16 10:43:27 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_widget_ml_config(object):
    def setupUi(self, widget_ml_config):
        widget_ml_config.setObjectName(_fromUtf8("widget_ml_config"))
        widget_ml_config.resize(1100, 826)
        self.widget_main_widget = QtGui.QWidget(widget_ml_config)
        self.widget_main_widget.setGeometry(QtCore.QRect(8, 10, 1078, 804))
        self.widget_main_widget.setStyleSheet(_fromUtf8(""))
        self.widget_main_widget.setObjectName(_fromUtf8("widget_main_widget"))
        self.label = QtGui.QLabel(self.widget_main_widget)
        self.label.setGeometry(QtCore.QRect(14, 23, 122, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.button_open_file = QtGui.QPushButton(self.widget_main_widget)
        self.button_open_file.setGeometry(QtCore.QRect(143, 23, 54, 37))
        self.button_open_file.setStyleSheet(_fromUtf8(""))
        self.button_open_file.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../assets/open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_open_file.setIcon(icon)
        self.button_open_file.setIconSize(QtCore.QSize(60, 40))
        self.button_open_file.setObjectName(_fromUtf8("button_open_file"))
        self.group_clustering = QtGui.QGroupBox(self.widget_main_widget)
        self.group_clustering.setGeometry(QtCore.QRect(30, 80, 901, 311))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.group_clustering.setFont(font)
        self.group_clustering.setStyleSheet(_fromUtf8("border-left-color: rgb(0, 0, 0);"))
        self.group_clustering.setAlignment(QtCore.Qt.AlignCenter)
        self.group_clustering.setFlat(False)
        self.group_clustering.setCheckable(False)
        self.group_clustering.setObjectName(_fromUtf8("group_clustering"))
        self.check_use_minibatch_clustering = QtGui.QCheckBox(self.group_clustering)
        self.check_use_minibatch_clustering.setGeometry(QtCore.QRect(10, 100, 193, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.check_use_minibatch_clustering.setFont(font)
        self.check_use_minibatch_clustering.setObjectName(_fromUtf8("check_use_minibatch_clustering"))
        self.layoutWidget = QtGui.QWidget(self.group_clustering)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 130, 98, 26))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_8.addWidget(self.label_9)
        self.combo_clusters = QtGui.QComboBox(self.layoutWidget)
        self.combo_clusters.setObjectName(_fromUtf8("combo_clusters"))
        self.horizontalLayout_8.addWidget(self.combo_clusters)
        self.horizontalLayout_8.setStretch(1, 1)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_8)
        self.button_clusterize = QtGui.QPushButton(self.group_clustering)
        self.button_clusterize.setGeometry(QtCore.QRect(20, 200, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.button_clusterize.setFont(font)
        self.button_clusterize.setObjectName(_fromUtf8("button_clusterize"))
        self.layoutWidget1 = QtGui.QWidget(self.group_clustering)
        self.layoutWidget1.setGeometry(QtCore.QRect(140, 190, 221, 106))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_13 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_9.addWidget(self.label_13)
        self.label_features_clustering = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_features_clustering.setFont(font)
        self.label_features_clustering.setText(_fromUtf8(""))
        self.label_features_clustering.setObjectName(_fromUtf8("label_features_clustering"))
        self.horizontalLayout_9.addWidget(self.label_features_clustering)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_11 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_14.addWidget(self.label_11)
        self.label_donein_clustering = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_donein_clustering.setFont(font)
        self.label_donein_clustering.setText(_fromUtf8(""))
        self.label_donein_clustering.setObjectName(_fromUtf8("label_donein_clustering"))
        self.horizontalLayout_14.addWidget(self.label_donein_clustering)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_10 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_13.addWidget(self.label_10)
        self.label_silhuette = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_silhuette.setFont(font)
        self.label_silhuette.setText(_fromUtf8(""))
        self.label_silhuette.setObjectName(_fromUtf8("label_silhuette"))
        self.horizontalLayout_13.addWidget(self.label_silhuette)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.button_save_clustering_config = QtGui.QPushButton(self.group_clustering)
        self.button_save_clustering_config.setGeometry(QtCore.QRect(400, 270, 33, 29))
        self.button_save_clustering_config.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../assets/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_save_clustering_config.setIcon(icon1)
        self.button_save_clustering_config.setIconSize(QtCore.QSize(33, 29))
        self.button_save_clustering_config.setObjectName(_fromUtf8("button_save_clustering_config"))
        self.layoutWidget2 = QtGui.QWidget(self.group_clustering)
        self.layoutWidget2.setGeometry(QtCore.QRect(12, 42, 241, 24))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_4 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.combo_vectorizer_clustering = QtGui.QComboBox(self.layoutWidget2)
        self.combo_vectorizer_clustering.setObjectName(_fromUtf8("combo_vectorizer_clustering"))
        self.horizontalLayout.addWidget(self.combo_vectorizer_clustering)
        self.layoutWidget3 = QtGui.QWidget(self.group_clustering)
        self.layoutWidget3.setGeometry(QtCore.QRect(680, 40, 195, 107))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.vlayout_checkboxes = QtGui.QVBoxLayout(self.layoutWidget3)
        self.vlayout_checkboxes.setMargin(0)
        self.vlayout_checkboxes.setObjectName(_fromUtf8("vlayout_checkboxes"))
        self.check_use_stemming_clustering = QtGui.QCheckBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.check_use_stemming_clustering.setFont(font)
        self.check_use_stemming_clustering.setObjectName(_fromUtf8("check_use_stemming_clustering"))
        self.vlayout_checkboxes.addWidget(self.check_use_stemming_clustering)
        self.check_use_idf_clustering = QtGui.QCheckBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.check_use_idf_clustering.setFont(font)
        self.check_use_idf_clustering.setObjectName(_fromUtf8("check_use_idf_clustering"))
        self.vlayout_checkboxes.addWidget(self.check_use_idf_clustering)
        self.check_binary_clustering = QtGui.QCheckBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.check_binary_clustering.setFont(font)
        self.check_binary_clustering.setObjectName(_fromUtf8("check_binary_clustering"))
        self.vlayout_checkboxes.addWidget(self.check_binary_clustering)
        self.check_remove_stopwords_clustering = QtGui.QCheckBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.check_remove_stopwords_clustering.setFont(font)
        self.check_remove_stopwords_clustering.setObjectName(_fromUtf8("check_remove_stopwords_clustering"))
        self.vlayout_checkboxes.addWidget(self.check_remove_stopwords_clustering)
        self.layoutWidget4 = QtGui.QWidget(self.group_clustering)
        self.layoutWidget4.setGeometry(QtCore.QRect(430, 30, 192, 119))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_5 = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.combo_ngram_range_clustering = QtGui.QComboBox(self.layoutWidget4)
        self.combo_ngram_range_clustering.setObjectName(_fromUtf8("combo_ngram_range_clustering"))
        self.horizontalLayout_2.addWidget(self.combo_ngram_range_clustering)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_6 = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.combo_max_df_clustering = QtGui.QComboBox(self.layoutWidget4)
        self.combo_max_df_clustering.setObjectName(_fromUtf8("combo_max_df_clustering"))
        self.horizontalLayout_4.addWidget(self.combo_max_df_clustering)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_7 = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_5.addWidget(self.label_7)
        self.combo_min_df_clustering = QtGui.QComboBox(self.layoutWidget4)
        self.combo_min_df_clustering.setObjectName(_fromUtf8("combo_min_df_clustering"))
        self.horizontalLayout_5.addWidget(self.combo_min_df_clustering)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_8 = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_6.addWidget(self.label_8)
        self.combo_max_features_clustering = QtGui.QComboBox(self.layoutWidget4)
        self.combo_max_features_clustering.setObjectName(_fromUtf8("combo_max_features_clustering"))
        self.horizontalLayout_6.addWidget(self.combo_max_features_clustering)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.layoutWidget5 = QtGui.QWidget(self.group_clustering)
        self.layoutWidget5.setGeometry(QtCore.QRect(620, 170, 260, 84))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.check_perform_lsa_clustering = QtGui.QCheckBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.check_perform_lsa_clustering.setFont(font)
        self.check_perform_lsa_clustering.setObjectName(_fromUtf8("check_perform_lsa_clustering"))
        self.verticalLayout.addWidget(self.check_perform_lsa_clustering)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_12 = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_3.addWidget(self.label_12)
        self.combo_n_components_clustering = QtGui.QComboBox(self.layoutWidget5)
        self.combo_n_components_clustering.setObjectName(_fromUtf8("combo_n_components_clustering"))
        self.horizontalLayout_3.addWidget(self.combo_n_components_clustering)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_14 = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_10.addWidget(self.label_14)
        self.label_explained_variance = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_explained_variance.setFont(font)
        self.label_explained_variance.setText(_fromUtf8(""))
        self.label_explained_variance.setObjectName(_fromUtf8("label_explained_variance"))
        self.horizontalLayout_10.addWidget(self.label_explained_variance)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.layoutWidget6 = QtGui.QWidget(self.widget_main_widget)
        self.layoutWidget6.setGeometry(QtCore.QRect(433, 24, 301, 24))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_3 = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_12.addWidget(self.label_3)
        self.label_percentage_stopwords = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_percentage_stopwords.setFont(font)
        self.label_percentage_stopwords.setText(_fromUtf8(""))
        self.label_percentage_stopwords.setObjectName(_fromUtf8("label_percentage_stopwords"))
        self.horizontalLayout_12.addWidget(self.label_percentage_stopwords)
        self.layoutWidget7 = QtGui.QWidget(self.widget_main_widget)
        self.layoutWidget7.setGeometry(QtCore.QRect(225, 24, 174, 24))
        self.layoutWidget7.setObjectName(_fromUtf8("layoutWidget7"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_11.setMargin(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_2 = QtGui.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_11.addWidget(self.label_2)
        self.label_lexical_diversity = QtGui.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_lexical_diversity.setFont(font)
        self.label_lexical_diversity.setText(_fromUtf8(""))
        self.label_lexical_diversity.setObjectName(_fromUtf8("label_lexical_diversity"))
        self.horizontalLayout_11.addWidget(self.label_lexical_diversity)

        self.retranslateUi(widget_ml_config)
        QtCore.QMetaObject.connectSlotsByName(widget_ml_config)

    def retranslateUi(self, widget_ml_config):
        widget_ml_config.setWindowTitle(_translate("widget_ml_config", "Form", None))
        self.label.setText(_translate("widget_ml_config", "Twitter dataset:", None))
        self.button_open_file.setToolTip(_translate("widget_ml_config", "open", None))
        self.group_clustering.setTitle(_translate("widget_ml_config", "Clustering", None))
        self.check_use_minibatch_clustering.setText(_translate("widget_ml_config", "use minibatch k-means", None))
        self.label_9.setText(_translate("widget_ml_config", "k:", None))
        self.button_clusterize.setToolTip(_translate("widget_ml_config", "clusterize data", None))
        self.button_clusterize.setText(_translate("widget_ml_config", "clusterize", None))
        self.label_13.setText(_translate("widget_ml_config", "features:", None))
        self.label_11.setText(_translate("widget_ml_config", "done in:", None))
        self.label_10.setText(_translate("widget_ml_config", "silhuette coeficient:", None))
        self.button_save_clustering_config.setToolTip(_translate("widget_ml_config", "save clustering config", None))
        self.label_4.setText(_translate("widget_ml_config", "vectorizer:", None))
        self.check_use_stemming_clustering.setText(_translate("widget_ml_config", "use stemming", None))
        self.check_use_idf_clustering.setText(_translate("widget_ml_config", "use idf", None))
        self.check_binary_clustering.setText(_translate("widget_ml_config", "binary", None))
        self.check_remove_stopwords_clustering.setText(_translate("widget_ml_config", "remove stopwords", None))
        self.label_5.setText(_translate("widget_ml_config", "ngram range:", None))
        self.label_6.setText(_translate("widget_ml_config", "max df:", None))
        self.label_7.setText(_translate("widget_ml_config", "min df:", None))
        self.label_8.setText(_translate("widget_ml_config", "max features: ", None))
        self.check_perform_lsa_clustering.setText(_translate("widget_ml_config", "perform lsa", None))
        self.label_12.setText(_translate("widget_ml_config", "number of components:", None))
        self.label_14.setText(_translate("widget_ml_config", "explained variance:", None))
        self.label_3.setText(_translate("widget_ml_config", "Percentage of stopwords:", None))
        self.label_2.setText(_translate("widget_ml_config", "Lexical diversity:", None))

